replicaCount: 2
api:
  version: ${API_VERSION}

image:
  repository: ghcr.io/cosmo-tech/cosmotech-api
  tag: ${CHART_PACKAGE_VERSION}
argo:
  imageCredentials:
    password: ${ACR_LOGIN_PASSWORD}
    registry: ${ACR_LOGIN_SERVER}
    username: ${ACR_LOGIN_USERNAME}
config:
  api:
    serviceMonitor:
      enabled: true
      namespace: ${MONITORING_NAMESPACE}
  csm:
    platform:
      namespace: ${NAMESPACE}
      argo:
        base-uri: "http://${ARGO_RELEASE_NAME}-argo-workflows-server.${NAMESPACE}.svc.cluster.local:2746"
        workflows:
          namespace: ${NAMESPACE}
          service-account-name: ${ARGO_SERVICE_ACCOUNT}
      azure:
        containerRegistries:
          solutions: ${ACR_LOGIN_SERVER}
        cosmos:
          key: ${COSMOS_KEY}
          uri: ${COSMOS_URI}
        credentials:
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
          tenantId: ${TENANT_ID}
        dataWarehouseCluster:
          baseUri: ${ADX_URI}
          options:
            ingestionUri: ${ADX_INGESTION_URI}
        eventBus:
          baseUri: ${EVENTBUS_URI}
        storage:
          account-key: ${STORAGE_ACCOUNT_KEY}
          account-name: ${STORAGE_ACCOUNT_NAME}
      twincache:
        host: "cosmotechredis-master.${NAMESPACE}.svc.cluster.local"
        port: ${REDIS_PORT}
        username: "default"
        password: ${REDIS_PASSWORD}

ingress:
  enabled: ${COSMOTECH_API_INGRESS_ENABLED}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.org/client-max-body-size: "0"
  hosts:
    - host: ${COSMOTECH_API_DNS_NAME}
  tls:
    - secretName: ${TLS_SECRET_NAME}
      hosts: ["${COSMOTECH_API_DNS_NAME}"]

resources:
  # Recommended in production environments
  limits:
    #   cpu: 100m
    memory: 2048Mi
  requests:
    #   cpu: 100m
    memory: 1024Mi

tolerations:
- key: "vendor"
  operator: "Equal"
  value: "cosmotech"
  effect: "NoSchedule"

nodeSelector:
  "cosmotech.com/tier": "services"